#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
if [ ${grub_platform} == "efi" ]; then
	menuentry "Firmware setup" {
		fwsetup
	}
	menuentry "Archlinux Netboot" {
		insmod fat
		insmod chain
		search --no-floppy --set=root --file /EFI/netboot/ipxe.efi
		chainloader /EFI/netboot/ipxe.efi
	}
fi
